version: '3'
services:
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.0
    volumes:
    - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      # so support single node development
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - web
      - default
    labels:
      - "traefik.backend=naturalis-elasticsearch"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=9200"
      - ${ELASTICSEARCH_URL_CONFIG:-traefik.frontend.rule=Host:insight-elasticsearch.naturalis.nl}
      - ${ELASTICSEARCH_AUTH:-traefik.frontend.auth.basic=kibana:$apr1$.lcgllId$9sUY3fPk/gDuh3NQ55024/}

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.0
    expose:
      - "5601"
    networks:
      - web
      - default
    labels:
      - "traefik.backend=naturalis-kibana"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=5601"
      - ${KIBANA_URL_CONFIG:-traefik.frontend.rule=Host:insight-kibana.naturalis.nl}
      - ${KIBANA_AUTH:-traefik.frontend.auth.basic=kibana:$apr1$.lcgllId$9sUY3fPk/gDuh3NQ55024/}

  grafana:
    #image: grafana/grafana
    image: grafana/grafana:master
    volumes:
      - ./grafana/data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASS:-secret}
    expose:
      - "3000"
    networks:
      - web
      - default
    labels:
      - "traefik.backend=naturalis-grafana"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=3000"
      - ${GRAFANA_URL_CONFIG:-traefik.frontend.rule=Host:insight.naturalis.nl}

  traefik:
    image: traefik:1.4.5
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TRAEFIK_TOML_FILE:-./traefik.dev.toml}:/traefik.toml
      - ${ACME_JSON:-./acme.json}:/acme.json
    container_name: traefik



# filebeat should not run in this cluser since it won't every really be
#
# ====================================================================
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.1.0
    network_mode: host
    #      - filebeat
        #    extra_hosts:
        #      - "insight-elasticsearch.naturalis.nl:127.0.0.1"
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/modules.d:/usr/share/filebeat/modules.d
      - ./filebeat/module:/usr/share/filebeat/module
      - ./filebeat/log:/log
      - ./filebeat/template:/template


# run docker network create web before
networks:
  web:
    external: true




